### PR TITLE
Switch from request to phin!

### PR DESCRIPTION
**Pull request by bdsomer**
[`request`](https://npmjs.com/package/request) is way too large and has way too many dependencies! Use [`phin`](https://npmjs.com/package/phin) instead!

### CODE REVIEW

**Comment by salimkayabasi** [comment]
hey @bdsomer thanks for your contribution :) I'll check your pr but in my opinion, just using native http request would be simplest solution for this one.

**Comment by bdsomer** [comment]
@salimkayabasi Okay then, I'll just keep this open if you would like to merge! Also, make sure to use the `https` module if you are going to implement it without any dependencies. You may also want to consider adding compression as well.

**Comment by salimkayabasi** [comment]
will add `compression` by default later. thanks for your valuable feedback

**Comment by salimkayabasi** [comment]
#12 will take care

**Pull request closed without merging**
